In [1]:
import pandas as pd
import glob
import os

In [3]:
bihar_tenders = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Deployment\flood-data-ecosystem-Bihar\Sources\TENDERS\tender_data_csv\all_tenders_bihar.csv')
bihar_tenders

,tenderid,tenderrefno,title,description,groupid,procurement_amount_pacamt,tendercurrency,bidcurrency,createdate_iso,updatedate_iso,...,issuing_address,issuing_email,issuing_contact_no,approving_authority_name,approving_authority_designation,approving_organization_name,approving_organization_code,emd_amount,tender_fee_amount,tender_processing_fee_amount
0,18397,31/BCD/MUNGER/2021-22,FURNITURE WORK FOR GOVERNMENT ENGINEERING COLL...,FURNITURE WORK FOR GOVERNMENT ENGINEERING COLL...,2462,51024760.0,INR,INR,2022-01-22T07:21:15.778000+00:00,2022-02-27T08:25:14+00:00,...,Fort Area munger,ee.munger.bcd@gmail.com,9113192054,Superintending Engineer Building Circle Munger,Superintending Engineer,Building Construction Department,Superintending Engineer Building Circle Munger,1020500.0,10000.0,5900.0
1,18398,BSMCL-08/2021-22/VAISHALI/CLUSTER-03,EC Approved Sand Ghat of VAISHALI (Cluster-03)...,EC Approved Sand Ghat of VAISHALI (Cluster-03)...,2598,8049273.0,INR,INR,2022-01-22T07:22:47.275000+00:00,2022-01-30T07:31:00+00:00,...,VIKASH BHAWAN PATNA,BHARRTI@GMAIL.COM,9852903038,NIDHI BHARTI,M.D.O,BIHAR STATE MINING CORPORATION LTD,NaN,2012319.0,29500.0,3540.0
2,18399,BSMCL-08/2021-22/VAISHALI/CLUSTER-04,EC Approved Sand Ghat of VAISHALI (Cluster-04)...,EC Approved Sand Ghat of VAISHALI (Cluster-04)...,2598,11751939.0,INR,INR,2022-01-22T07:40:30.789000+00:00,2022-01-30T07:31:00+00:00,...,VIKASH BHAWAN PATNA,BHARRTI@GMAIL.COM,9852903038,NIDHI BHARTI,M.D.O,BIHAR STATE MINING CORPORATION LTD,NaN,2937984.0,29500.0,3540.0
3,18400,BSMCL-08/2021-22/BANKA/CLUSTER-02,EC APPROVED SANDGHATS OF BANKA (CLUSTER-02)\nP...,EC APPROVED SANDGHATS OF BANKA (CLUSTER-02)\nP...,2598,75320669.0,INR,INR,2022-01-22T08:18:32.137000+00:00,2022-01-30T07:31:00+00:00,...,"VIKASH BHAWAN, PATNA",bih.minescorp@gmail.com,9386768129,ANIL KUMAR,MDO,Bihar State Mining Corporation Limited,BSMCL,18830167.0,29500.0,5900.0
4,18401,"01/2021-22 MID, Nalanda",Renovation of Ghosrawan Pond Scheme,Renovation of Ghosrawan Pond Scheme,2462,4831400.0,INR,INR,2022-01-22T08:37:23.974000+00:00,2022-02-17T09:13:47+00:00,...,"JAL BHAWAN, RIDING ROAD, SHEKHPURA, PATNA- 800014",eepat-mi-bih@nic.in,9199424770,"ER. RAJENDRA KUMAR, SE PATNA",SUPERINTENDENT ENGINEER,"MINOR IRRIGATION CIRCLE, PATNA",MWRD BIHAR,48400.0,5000.0,590.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3894,53628,06/2023-24 (G-19),Ward sankhya 15 antargat Mukesh Gupta ke Ghar ...,Ward sankhya 15 antargat Mukesh Gupta ke Ghar ...,2462,1553649.0,INR,INR,2024-01-13T12:43:34.037000+00:00,2024-02-06T10:18:20+00:00,...,Nagar Parishad Raxaul,raxaululb@gmail.com,9540617654,Mr Manish Kumar (Executive Officer),Executive Officer Raxaul,"Nagar Parishad, Raxaul",801282,31100.0,5000.0,590.0
3895,53629,06/2023-24 (G-20),Ward sankhya 6 antargat Rajkumar Pande ke Ghar...,Ward sankhya 6 antargat Rajkumar Pande ke Ghar...,2462,671469.0,INR,INR,2024-01-13T12:47:12.732000+00:00,2024-02-06T10:20:31+00:00,...,Nagar Parishad Raxaul,raxaululb@gmail.com,9540617654,Mr Manish Kumar (Executive Officer),Executive Officer Raxaul,"Nagar Parishad, Raxaul",801282,9600.0,750.0,590.0
3896,53630,06/2023-24 (G-21),Ward sankhya 5 antar gat shivpujan sah ke Ghar...,Ward sankhya 5 antar gat shivpujan sah ke Ghar...,2462,2016897.0,INR,INR,2024-01-13T12:52:19.022000+00:00,2024-02-06T10:22:46+00:00,...,Nagar Parishad Raxaul,raxaululb@gmail.com,9540617654,Mr Manish Kumar (Executive Officer),Executive Officer Raxaul,"Nagar Parishad, Raxaul",801282,40500.0,5000.0,590.0
3897,53631,06/2023-24 (G-22),Ward sankhya 25 mein doctor madan Prasad ke Gh...,Ward sankhya 25 mein doctor madan Prasad ke Gh...,2462,2689554.0,INR,INR,2024-01-13T12:56:22.220000+00:00,2024-02-06T10:25:42+00:00,...,Nagar Parishad Raxaul,raxaululb@gmail.com,9540617654,Mr Manish Kumar (Executive Officer),Executive Officer Raxaul,"Nagar Parishad, Raxaul",801282,54000.0,5000.0,590.0
3898,53632,06/2023-24 (G-23),Ward sankhya 22 mein sthit Sonu Singh ke Ghar ...,Ward sankhya 22 mein sthit Sonu Singh ke Ghar ...,2462,1279302.0,INR,INR,2024-01-13T13:02:00.045000+00:00,2024-02-06T10:27:17+00:00,...,Nagar Parishad Raxaul,raxaululb@gmail.com,9540617654,Mr Manish Kumar (Executive Officer),Executive Officer Raxaul,"Nagar Parishad, Raxaul",801282,25600.0,2500.0,590.0

In [5]:
total_value = bihar_tenders['procurement_amount_pacamt'].sum()
total_value

56103517831.060005

In [6]:
up_tenders = up_tenders.loc[up_tenders['Status'] == 'Accepted-AOC']
up_tenders

,Unnamed: 0,Tender ID,tender_externalreference,tender_title,Work Description,Tender Category,Tender Type,Form of contract,Product Category,Is Multi Currency Allowed For BOQ,...,tender_district_externalReference,tender_district_title_description,tender_district_location,DISTRICT_FINALISED,tender_villages,tender_block,tender_subdistrict,gp,tender_block_location,BLOCK_FINALISED
0,794,2021_CEBBS_65546_30,Bid Identification No. EE-AID-12-2020-21,Protection to scoured bank on Lingara left nea...,Protection to scoured bank on Lingara left nea...,Works,Open Tender,Percentage,Civil Works - Others,No,...,NaN,Anugul,NaN,Anugul,"'MAJHIKA', 'BANARPAL'",BANARPAL,NaN,BANARPAL,BANARPAL,BANARPAL
5,2286,2021_RWSS_70806_2,04/SE/RWSS/ANGUL/2021-22(JJM),RPWS schemes from 40LPCD to 70LPCD to villages...,Retrofitting for RPWS scheme from 40LPCD to 70...,Works,National Competitive Bid,Turn-key,Civil Works - Water Works,No,...,NaN,Anugul,NaN,Anugul,"'EKAGHARIA', 'BANARPAL'",BANARPAL,NaN,BANARPAL,BANARPAL,BANARPAL
39,3451,2022_CEBBS_84530_5,SE-AID-6/2022-23,Protection to Scoured Bank on Right Bank of Ri...,Protection to Scoured Bank on Right Bank of Ri...,Works,Open Tender,Percentage,Civil Works - Others,No,...,NaN,Anugul,NaN,Anugul,"'TAKUA', 'KANIHA'",KANIHA,NaN,KANIHA,KANIHA,KANIHA
78,438,2021_CELBB_66256_15,EEPRD-20 OF 2020-21,PRD-15-Restoration to Daya Right Embankment fr...,"Earth work, Stone packing and dumping work",Works,National Competitive Bid,Percentage,Civil Works - Others,No,...,NaN,NaN,Khordha,Khordha,NaN,NaN,NaN,NaN,LANJIGARH,LANJIGARH
100,506,2021_IDCO_65684_1,PC/EST/E-59/2020-21,Provision of treated effluent distribution sys...,Provision of treated effluent distribution sys...,Works,National Competitive Bid,Percentage,Civil Works - Water Works,No,...,NaN,NaN,Khordha,Khordha,NaN,NaN,NaN,NaN,KHORDHA,KHORDHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4099,3014,2022_CCEJE_82163_1,SEUKID 01/2022-23 (SL 5),Construction of Protection wall on both banks ...,Canal Structural work,Works,Open Tender,Percentage,Civil Works - Canal,No,...,NaN,Mayurbhanj,Koraput,CONFLICT,NaN,NaN,NaN,NaN,NaN,NaN
4103,3098,2022_OBCC_82729_4,NO.42/TOLL/OBCC/2022-23,Surubalijore Bridge toll gate on Subalaya Dhar...,Surubalijore Bridge toll gate on Subalaya Dhar...,Works,Open Tender,Lump-sum,Toll Gate,No,...,NaN,Jajapur,Sonepur,CONFLICT,NaN,NaN,NaN,NaN,NaN,NaN
4105,3356,2022_CEBMB_81568_6,"ACE,RBB-20/2022-23","Improvement to Kushapalli Minor, Mareipalli Su...","Improvement to Kushapalli Minor, Mareipalli Su...",Works,National Competitive Bid,Percentage,Civil Works - Others,No,...,NaN,Sambalpur,Ganjam,CONFLICT,NaN,NaN,NaN,NaN,NaN,NaN
4113,3830,2021_CEBMB_68091_55,e-BNID-01/ 2021-22,Improvement to RFB of river Badanadi between R...,Restoration of Embankment,Works,Open Tender,Percentage,Civil Works - Others,No,...,NaN,Gajapati,Ganjam,CONFLICT,NaN,NaN,NaN,NaN,NaN,NaN
4115,3892,2022_CCEJE_83477_1,SE-UKHWD-05/2022-23(Sl.No.12),Construction of new protection walls of Padmap...,Canal structural work.,Works,Open Tender,Percentage,Civil Works - Canal,No,...,NaN,Rayagada,Koraput,CONFLICT,NaN,NaN,NaN,NaN,NaN,NaN